from app.schemas.user import (
    UserBase,
    UserCreate,
    UserUpdate,
    UserResponse,
    UserListResponse,
    UserLogin,
    Token,
    TokenData
)
from app.schemas.solicitud_vacaciones import (
    SolicitudVacacionesBase,
    SolicitudVacacionesCreate,
    SolicitudVacacionesUpdate,
    SolicitudVacacionesAprobacion,
    SolicitudVacacionesResponse
)
from app.schemas.incidencia import (
    IncidenciaBase,
    IncidenciaCreate,
    IncidenciaUpdate,
    IncidenciaResponse
)
from app.schemas.cliente import (
    ClienteBase,
    ClienteCreate,
    ClienteUpdate,
    ClienteResponse
)
from app.schemas.orden_trabajo import (
    CategoriaOrdenBase,
    CategoriaOrdenCreate,
    CategoriaOrdenResponse,
    SubcategoriaOrdenBase,
    SubcategoriaOrdenCreate,
    SubcategoriaOrdenResponse,
    SubtareaOrdenBase,
    SubtareaOrdenCreate,
    SubtareaOrdenUpdate,
    SubtareaOrdenResponse,
    OrdenTrabajoBase,
    OrdenTrabajoCreate,
    OrdenTrabajoUpdate,
    OrdenTrabajoResponse,
    OrdenTrabajoListResponse,
    CambiarEstadoOrden,
    UploadFotoRequest
)

__all__ = [
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "UserListResponse",
    "UserLogin",
    "Token",
    "TokenData",
    "SolicitudVacacionesBase",
    "SolicitudVacacionesCreate",
    "SolicitudVacacionesUpdate",
    "SolicitudVacacionesAprobacion",
    "SolicitudVacacionesResponse",
    "IncidenciaBase",
    "IncidenciaCreate",
    "IncidenciaUpdate",
    "IncidenciaResponse",
    "ClienteBase",
    "ClienteCreate",
    "ClienteUpdate",
    "ClienteResponse",
    "CategoriaOrdenBase",
    "CategoriaOrdenCreate",
    "CategoriaOrdenResponse",
    "SubcategoriaOrdenBase",
    "SubcategoriaOrdenCreate",
    "SubcategoriaOrdenResponse",
    "SubtareaOrdenBase",
    "SubtareaOrdenCreate",
    "SubtareaOrdenUpdate",
    "SubtareaOrdenResponse",
    "OrdenTrabajoBase",
    "OrdenTrabajoCreate",
    "OrdenTrabajoUpdate",
    "OrdenTrabajoResponse",
    "OrdenTrabajoListResponse",
    "CambiarEstadoOrden",
    "UploadFotoRequest"
]
